### ISSUE TITLE
Greengrass Error with Huge SFC Configs

### ISSUE THREAD

**Issue by qoomon** [aws-samples/shopfloor-connectivity#7]
Hi there,

Currently I build my sfc component with the [gdk](https://github.com/aws-greengrass/aws-greengrass-gdk-cli) and using the same approach [as you do](https://github.com/aws-samples/shopfloor-connectivity/blob/b874de27eddd9c49c8e5c3e040fd76d0723cdd77/deployment/greengrass-sfc-components/local-build-as-components-py/buildSfcComponentRecipes.py#L93) to create the sfc config from a greengrass config field.

However I run into an issue, if the config gets quite big. If your config exceed a character length of `getconf ARG_MAX` (in my case `1048576`) then greengrass nucleus throws `Argument list too long	at java.lang.ProcessBuilder.start`. This is because the workaround of an environment variable to access the sfc-config as JSON  counts also against that argument limit. Maybe it would make sense to implement a feature to reuse channel configs for a `Source`, maybe a something like `SourceTemplates`

In our use case the config is that big, because we have one IPC that crawls multiple S7 PLCs with over 1000 Channels (don't ask why :-D, it because of customer "reasons". ). One reason the config gets so big is the repetitions of the same channel configs for every PLC.

So I fiddled around and came up with following solution to generate the `sfc-config.json`:.
`recipe.yaml` excerpt
```yaml
        Lifecycle:
            Install:
                RequiresPrivilege: true # due to access /greengrass/v2/config/effectiveConfig.yaml
                Script: |
                    chmod +x '{artifacts:decompressedPath}/greengrass-sfc-playground/bin/yq_linux_arm'
                    alias yq='{artifacts:decompressedPath}/greengrass-sfc-playground/bin/yq_linux_arm'
                   
                    COMPONENT_NAME="$(basename $PWD)"
                
                    cat /greengrass/v2/config/effectiveConfig.yaml \
                        | yq ".services.\"${COMPONENT_NAME}\".configuration.sfc-config" \
                            --output-format=json \
                                > "sfc-config.json"
            Run:
                RequiresPrivilege: true # due to access /greengrass/v2/config/effectiveConfig.yaml
                Script: |
                    export SFC_DEPLOYMENT_DIR='{artifacts:decompressedPath}/greengrass-sfc-playground/sfc-modules'
                    alias sfc-main='{artifacts:decompressedPath}/greengrass-sfc-playground/sfc-main/bin/sfc-main'

                    sfc-main -config sfc-config.json
```

My approach is to read the sfc-config from the `/greengrass/v2/config/effectiveConfig.yaml`. In my current solution I bundled a yq binary to process the greengrass config, extract the sfc-config and transform the result to a `sfc-config.json`.

By this the config size is no longer limited by the environment `ARG_MAX` configuration. 

Only drawback and inconvenience is that I need to bundle a yaml processor. Therefore it would be awesome if `sfc-main` would support configs from `/greengrass/v2/config/effectiveConfig.yaml`. sfc already reads this file so it should be quite easy to implement it I guess. I think of something like 
```sh
sfc-main -config greengrass:<Component Name>:<JSON Path>
``` 
e.g.
```sh
sfc-main -config greengrass:com.example.sfc:sfc-config
``` 

WDYT?

**Comment by qoomon** [comment]
It seems that my solution does not work because it looks like the `effectiveConfig.yaml` only contains components initial configs :-(

**Comment by qoomon** [comment]
I make it work with following config
```yaml
        Lifecycle:
            Install:
                RequiresPrivilege: true # to access /greengrass/v2/bin/greengrass-cli
                Script: |
                    apt install jq -y
                    
                    COMPONENT_NAME="$(basename $PWD)"
                    /greengrass/v2/bin/greengrass-cli component details --name "${COMPONENT_NAME}" \
                        | grep "^ *Configuration: *" | sed 's/ *Configuration: *//' \
                        | jq -r '.sfc-config' > sfc-config.json
            Run:
                Setenv:
                    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-armhf
                RequiresPrivilege: true # /greengrass/v2/config/effectiveConfig.yaml (Permission denied)
                Script: |
                    export SFC_DEPLOYMENT_DIR='{artifacts:decompressedPath}/greengrass-sfc-playground/sfc-modules'
                    alias sfc-main='{artifacts:decompressedPath}/greengrass-sfc-playground/sfc-main/bin/sfc-main'
                    sfc-main -config sfc-config.json
```

**Comment by qoomon** [comment]
Here is my final recipe.yaml. 
- It will handle large 
- It will automatically configure Greengrass as the IoT Credential Provider
```yaml
RecipeFormatVersion: '2020-01-25'
ComponentName: '{COMPONENT_NAME}'
ComponentVersion: '{COMPONENT_VERSION}'
ComponentDescription: This is simple SFC example.
ComponentPublisher: '{COMPONENT_AUTHOR}'
ComponentConfiguration:
    DefaultConfiguration:
        sfc-config: # see https://github.com/aws-samples/shopfloor-connectivity/tree/mainline/docs
            AWSVersion: 2022-04-02
            Name: CONFIG_NAME
            Version: 1,
            LogLevel: Warn
            Schedules:
                -   Name: Demo
                    Active: true
                    Interval: 60000
                    Sources: { }
                    Targets:
                        - DebugTarget


ComponentDependencies:
    aws.greengrass.Cli:
        VersionRequirement: '^2.0.0'
        DependencyType: SOFT

Manifests:
    -   Artifacts:
            -   URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/greengrass-sfc-playground.zip
                Unarchive: ZIP
                Permission:
                    Execute: OWNER
        Platform:
            os: linux
        Lifecycle:
            Install:
                RequiresPrivilege: true # is required to access GREENGRASS_DEPLOYMENT_PATH/bin/greengrass-cli
                Script: |
                    apt-get install jq -y
                    
                    GREENGRASS_DEPLOYMENT_PATH='/greengrass/v2'
                    COMPONENT_NAME="$(basename $PWD)"
                    
                    SFC_CONFIG_FILE_NAME='sfc-config.json'
                    
                    # get sfc configuration from component configuration object field 'sfc-config' by greengrass-cli
                    "${GREENGRASS_DEPLOYMENT_PATH}/bin/greengrass-cli" component details --name "${COMPONENT_NAME}" \
                        | grep "^ *Configuration: *" | sed 's/ *Configuration: *//' \
                        | jq -r '."sfc-config"' > "${CONFIG_FILE_NAME}"
                    
                    # adjust sfc configuration to use greengrass as aws iot credential provider 
                    echo "$(jq  --arg GreenGrassDeploymentPath  "${GREENGRASS_DEPLOYMENT_PATH}" \
                            '.AwsIotCredentialProviderClients.AwsIotClient.GreenGrassDeploymentPath = $GreenGrassDeploymentPath' \
                            "${SFC_CONFIG_FILE_NAME}")" > "${SFC_CONFIG_FILE_NAME}"
            Run:
                Setenv:
                    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-armhf
                RequiresPrivilege: true # is required for sfc to access GREENGRASS_DEPLOYMENT_PATH/config/effectiveConfig.yaml
                Script: |
                    export SFC_DEPLOYMENT_DIR='{artifacts:decompressedPath}/greengrass-sfc-playground/sfc-modules'
                    {artifacts:decompressedPath}/greengrass-sfc-playground/sfc-main/bin/sfc-main -config sfc-config.json
```
